defaults:
  - args
  - _self_
  - task@_global_: atari/pong

username: 'slerman'
conda: 'source /home/slerman/miniconda3/bin/activate ML'
num_gpus: 1
gpu: 'K80|V100|A100|RTX'
mem: 20
time: '5-00:00:00'
lab: false
reservation_id: null
task: ${suite}/${task_name}

hydra:
  run:
    dir: ./
  sweep:
    dir: ./
    subdir: ./
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper